### ISSUE TITLE
Upload mobile.css 

### ISSUE THREAD

**Issue by mmiyahara** [kintone/customize-uploader#145]
According to the update info below, it seems like kintone will support CSS files for mobile devices.
  
  [2019/06/09の定期メンテナンスにおける cybozu.com 共通、kintone API更新情報 (2019/05/10)
](https://developer.cybozu.io/hc/ja/articles/360027483211)

kintone-customize-uploader should be able to handle mobile.css as well.

**Comment by koba04** [comment]
@mmiyahara 
Yeah, I've already added mobile CSS support by https://github.com/kintone/customize-uploader/pull/139.
You can try this as an alpha version.
Please try it 👍 

```
npm i -D @kintone/customize-uploader@next
```

**Comment by mmiyahara** [comment]
@koba04 
I didn't notice that you already implemented it! Awesome!
I don't have any kintone environments to try this feature right now, but I'll do as soon as I get one.
Let me close this issue then. Thanks always!
